name: template01
services:
  api-gateway:
    build:
      context: ./api-gateway-service  # Updated directory for the API Gateway service
      dockerfile: Dockerfile
    image: expense-tool-saas-api-gateway-service:latest
    environment:
      - ENVIRONMENT=production 
    volumes:
      - ./api-gateway-service:/code  # Sync the correct directory for the API Gateway service
    depends_on:
      - postgres_db
      - broker
      - redis
    ports:
      - "8000:8000"  # Expose container port 8085 to host port 8085

  user-service:
    build:
      context: ./user-service  # Updated directory for the API Gateway service
      dockerfile: Dockerfile
    image: expense-tool-saas-user-service:latest
    volumes:
      - ./user-service:/code  # Sync the correct directory for the API Gateway service
    depends_on:
      - postgres_db
      - broker
      - redis
    ports:
      - "8010:8010"  # Expose container port 8085 to host port 8085

  postgres_db:
    image: postgres:latest  # Use the official PostgreSQL image
    restart: always
    container_name: PostgresCont
    environment:
      - POSTGRES_USER=shahzaibse
      - POSTGRES_PASSWORD=my_password
      - POSTGRES_DB=mydatabase
    ports:
      - '5433:5432'  # Or change to 5432:5432 if you want the default port
    volumes:
      - postgres_db:/var/lib/postgresql/data

  broker:
    image: bitnami/kafka:3.7.0  # Updated to a Kafka image supporting KRaft mode
    container_name: broker
    ports:
      - '9092:9092'
    environment:
      KAFKA_ENABLE_KRAFT: "yes"  # Enable KRaft mode
      KAFKA_CFG_NODE_ID: 1
      KAFKA_CFG_PROCESS_ROLES: "broker,controller"
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: "1@broker:9093"
      KAFKA_CFG_LISTENERS: "PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093"
      KAFKA_CFG_ADVERTISED_LISTENERS: "PLAINTEXT://broker:9092"
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_CFG_LOG_DIRS: "/tmp/kraft-combined-logs"
      KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CFG_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    volumes:
      - ./kafka_logs:/opt/kafka/kraft-logs  # Optional: Persistent storage for logs

  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: 'Local Kafka Cluster'
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: 'broker:9092'
      DYNAMIC_CONFIG_ENABLED: "true"
    depends_on:
      - broker

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"

volumes:
  postgres_db:
    driver: local
  kafka_logs:
    driver: local

networks:
  default:
    driver: bridge
